### ISSUE TITLE
Content Relative to Caller

### ISSUE THREAD

**Issue by soloam** [thomasloven/lovelace-popup-card#23]
Hello, is it possible to have the content of the card relative to the caller Attributes? I set the card to repeat across several entities... all of them have the same Attributes names, and I would like to have a card to all of them... accessing his own attributes.

Is this possible or planed? 

Thank You

**Comment by kloggy** [comment]
I think I have the same question.
This popup-card in conjunction with the custom button card is a match made in heaven!

My door, window and motion sensors sometimes get in the wrong state. I have a view set up with an `input_select` for each one so that I can manually change their state.

I have another view that shows all the sensors using buttons and I'd like to define the tap action for all of those buttons so that when a sensor is in the wrong state I can pop up a card with the correct `input_select` for that sensor.

I guess the short question is could it be possible to make the entities used in the popup-card templateable?

**Comment by thomasloven** [comment]
You could probably do it with some backend help with [browser-commander](https://github.com/thomasloven/lovelace-browser-commander) or automatically generate the cards with some help from a soon-to-be-released feature of [lovelace-gen](https://github.com/thomasloven/homeassistant-lovelace-gen)
